json.id battle.id
json.battle_cluster_id battle.battle_cluster_id
json.win battle.win
json.win_initiative battle.win_initiative
json.dmg_taken battle.dmg_taken
json.dmg_dealt battle.dmg_dealt
json.turns battle.turns
json.hits battle.hits
json.misses battle.misses
json.crits battle.crits
json.atk_1_rate battle.atk_1_rate
json.atk_2_rate battle.atk_2_rate
json.atk_3_rate battle.atk_3_rate